/**
 * Editor side panels — FlowTree (full journey), ChangeLogPanel (AI export),
 * SessionsPanel (save history), InsertMenu (add text/button/note).
 */
import { useMemo, useState } from "react";
import config from "../../../canvas.config";
import { SURFACES, WORKSPACES, getSurface } from "./registry";
import { useCanvasStore, useCanvasState } from "./store";
import type { ChangeEntry } from "../../../shared/changeSchema";

const FONT = config.uiFont;
const ACCENT = config.accent;
const S = {
  h: { fontSize: 11, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase", color: "rgba(17,17,17,0.45)", fontFamily: FONT, padding: "14px 16px 8px" } as React.CSSProperties,
  item: { padding: "7px 16px", fontSize: 12.5, fontFamily: FONT, cursor: "pointer", color: "#111", display: "flex", alignItems: "center", gap: 8 } as React.CSSProperties,
  btn: { padding: "8px 14px", borderRadius: 8, border: "1px solid rgba(17,17,17,0.14)", background: "#fff", fontSize: 12, fontFamily: FONT, fontWeight: 700, cursor: "pointer", color: "#111" } as React.CSSProperties,
  mono: { fontFamily: "ui-monospace, monospace" } as React.CSSProperties,
};

/** The first surface in the inventory acts as the journey root for the flow tree. */
const ROOT_SURFACE = SURFACES[0]?.id ?? "";

// ─── Flow tree ────────────────────────────────────────────────────────────────
export function FlowTree({ onJump }: { onJump: (surfaceId: string) => void }) {
  // Build journey tree: BFS from the root surface following nav edges
  const tree = useMemo(() => {
    const visited = new Set<string>();
    const lines: { id: string; depth: number; via: string }[] = [];
    const walk = (id: string, depth: number, via: string) => {
      if (visited.has(id) || depth > 8) return;
      visited.add(id);
      lines.push({ id, depth, via });
      const s = getSurface(id);
      s?.nav.forEach((n) => { if (!n.to.startsWith("toast:")) walk(n.to, depth + 1, n.trigger); });
    };
    if (ROOT_SURFACE) walk(ROOT_SURFACE, 0, "");
    // orphans (not reachable from the root)
    SURFACES.forEach((s) => { if (!visited.has(s.id)) lines.push({ id: s.id, depth: 0, via: "(direct)" }); });
    return lines;
  }, []);

  return (
    <div style={{ overflowY: "auto", height: "100%" }}>
      <p style={S.h}>User journey · {tree.length} surfaces</p>
      {tree.map((l, i) => {
        const s = getSurface(l.id);
        if (!s) return null;
        return (
          <div
            key={`${l.id}-${i}`}
            style={{ ...S.item, paddingLeft: 16 + l.depth * 14 }}
            onClick={() => onJump(l.id)}
            title={l.via ? `via: ${l.via}` : undefined}
          >
            <span style={{ width: 6, height: 6, borderRadius: 3, background: s.type === "screen" ? "#111111" : s.type === "screen-state" ? "rgba(17,17,17,0.35)" : ACCENT, flexShrink: 0 }} />
            <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
              {s.name}
              <span style={{ color: "rgba(17,17,17,0.35)", fontSize: 10.5, marginLeft: 6 }}>{s.type !== "screen" ? s.type : ""}</span>
            </span>
          </div>
        );
      })}
    </div>
  );
}

// ─── Change log panel ─────────────────────────────────────────────────────────

/** Repo lines for export headers, from canvas.config.ts. */
function repoHeaderLines(): string[] {
  const r = config.repos;
  const lines: string[] = [];
  if (r.web) lines.push(`> Web source repo: \`${r.web}\` — \`sourceFile:line\` anchors and \`codeRefs.web\` paths are relative to it.`);
  if (r.ios) lines.push(`> iOS source repo: \`${r.ios}\` — \`codeRefs.ios\` paths are relative to it.`);
  if (r.android) lines.push(`> Android source repo: \`${r.android}\` — \`codeRefs.android\` paths are relative to it.`);
  return lines;
}

export function toMarkdown(log: ChangeEntry[]): string {
  const head = [
    `# ${config.projectName} — Design Canvas Change Log (for AI coding agents)`,
    "",
    "> Generated by Design Canvas. Each entry anchors to a real source location.",
    ...repoHeaderLines(),
    "> Apply changes to the web source first; other platforms follow via codeRefs.",
    "",
  ];
  const rows = log.map((c) => {
    const s = getSurface(c.surface);
    const lines = [
      `## ${c.id} · ${c.op.toUpperCase()} · ${s?.name ?? c.surface}`,
      "",
      `| Field | Value |`,
      `|---|---|`,
      `| Workspace | ${c.workspace} |`,
      `| Surface | \`${c.surface}\` (${c.surfaceType}) |`,
      `| Element | ${c.elementRole || "—"} \`${c.elementId}\` |`,
      `| Source | \`${c.sourceFile}${c.line ? `:${c.line}` : ""}\` |`,
      s?.codeRefs?.web ? `| Web file | \`${s.codeRefs.web}\` |` : "",
      s?.codeRefs?.ios ? `| iOS file | \`${s.codeRefs.ios}\` |` : "",
      s?.codeRefs?.android ? `| Android file | \`${s.codeRefs.android}\` |` : "",
      `| Property | ${c.property || "—"} |`,
      `| Before | \`${JSON.stringify(c.before)}\` |`,
      `| After | \`${JSON.stringify(c.after)}\` |`,
      c.insertedSpec ? `| Inserted spec | \`${JSON.stringify(c.insertedSpec)}\` |` : "",
      c.deletedSnapshot ? `| Deleted snapshot | \`${JSON.stringify(c.deletedSnapshot).slice(0, 300)}\` |` : "",
      `| Off-palette | ${c.offPalette ? "**YES — needs approval**" : "no"} |`,
      c.notes ? `| Notes | ${c.notes} |` : "",
      `| Timestamp | ${c.timestamp} |`,
      "",
      `**Acceptance criteria:** ${acceptance(c, s?.name ?? c.surface)}`,
      "",
    ].filter(Boolean);
    return lines.join("\n");
  });
  return [...head, ...rows].join("\n");
}

/** One verifiable acceptance criterion per entry, for the coding agent. */
function acceptance(c: ChangeEntry, surfaceName: string): string {
  const anchor = `\`${c.sourceFile}${c.line ? `:${c.line}` : ""}\``;
  switch (c.op) {
    case "edit":
      if (c.property === "text") return `The element at ${anchor} renders the exact text ${JSON.stringify(c.after)} instead of ${JSON.stringify(c.before)} on ${surfaceName}.`;
      if (c.property === "color" || c.property === "background") return `The ${c.property} of the element at ${anchor} is ${JSON.stringify(c.after)}${c.offPalette ? " (OFF-PALETTE — confirm with the design owner before applying)" : ""}.`;
      return `The ${c.property} of the element at ${anchor} equals ${JSON.stringify(c.after)}.`;
    case "move": return `The element at ${anchor} is offset by ${JSON.stringify(c.after)} px from its original position (use transform/layout-safe spacing).`;
    case "resize": return `The element at ${anchor} measures ${JSON.stringify(c.after)} in CSS px at ${config.device.width}px frame width.`;
    case "add": return `A new element matching the inserted spec exists near anchor \`${c.anchorElement}\` at offset ${JSON.stringify(c.position)} on ${surfaceName}.`;
    case "delete": return `The element at ${anchor} no longer renders on ${surfaceName}; deletedSnapshot preserved above for restore.`;
    case "hide": return `The element at ${anchor} is not visible on ${surfaceName}.`;
    case "show": return `The element at ${anchor} is visible again on ${surfaceName}.`;
    case "annotate": return `Directive satisfied: ${JSON.stringify(c.after)} (element at ${anchor}).`;
    default: return `Change at ${anchor} is applied exactly as specified above.`;
  }
}

export function ChangeLogPanel({ onJump }: { onJump: (surfaceId: string) => void }) {
  const changeLog = useCanvasState((s) => s.changeLog);
  const store = useCanvasStore();
  const [copied, setCopied] = useState<string | null>(null);

  const download = (content: string, filename: string, mime: string) => {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
  };

  const copy = async (content: string, tag: string) => {
    await navigator.clipboard.writeText(content);
    setCopied(tag);
    setTimeout(() => setCopied(null), 1600);
  };

  const json = JSON.stringify({ version: 1, generatedAt: new Date().toISOString(), project: config.projectName, repos: config.repos, changes: changeLog }, null, 2);
  const md = toMarkdown(changeLog);

  // GitHub issue export — only when canvas.config.ts sets githubIssueRepo.
  const issueRepo = config.githubIssueRepo;
  const openGitHubIssue = () => {
    if (!issueRepo) return;
    const title = `Design review: ${changeLog.length} change(s) from Design Canvas — ${new Date().toISOString().slice(0, 10)}`;
    const bodyFull = [
      "## Summary",
      "",
      `${changeLog.length} visual change(s) captured in the ${config.projectName} Design Canvas. Each entry below anchors to real source locations; apply per the mapped codeRefs.`,
      "",
      md,
      "",
      "---",
      "_Exported from Design Canvas._",
    ].join("\n");
    // GitHub URL length limit ~8k chars: truncate body if needed and note the full export.
    const maxBody = 6500;
    const body = bodyFull.length > maxBody
      ? `${bodyFull.slice(0, maxBody)}\n\n…\n\n**Body truncated — attach the full Markdown export (Download MD) to this issue.**`
      : bodyFull;
    const url = `https://github.com/${issueRepo}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;
    window.open(url, "_blank", "noopener");
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingRight: 12 }}>
        <p style={S.h}>Change log · {changeLog.length}</p>
        <div style={{ display: "flex", gap: 6 }}>
          {changeLog.length > 0 && (
            <button style={{ ...S.btn, padding: "4px 10px", fontSize: 11 }} onClick={() => store.undoLast()} title="Undo last change (Ctrl+Z)">Undo</button>
          )}
          <button style={{ ...S.btn, padding: "4px 10px", fontSize: 11 }} onClick={() => store.redoLast()} title="Redo (Ctrl+Y or Ctrl+Shift+Z)">Redo</button>
        </div>
      </div>
      <div style={{ flex: 1, overflowY: "auto" }}>
        {changeLog.length === 0 && (
          <p style={{ padding: "8px 16px", fontSize: 12.5, color: "rgba(17,17,17,0.45)", fontFamily: FONT, lineHeight: 1.6 }}>
            No changes yet. Every add, edit, delete, move, and resize you make is captured here with exact source anchors.
          </p>
        )}
        {changeLog.slice().reverse().map((c) => (
          <div key={c.id} style={{ padding: "9px 16px", borderBottom: "1px solid rgba(17,17,17,0.05)", cursor: "pointer" }} onClick={() => onJump(c.surface)}>
            <div style={{ display: "flex", gap: 6, alignItems: "center", marginBottom: 3 }}>
              <span style={{
                fontSize: 9.5, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase", fontFamily: FONT,
                padding: "2px 7px", borderRadius: 100,
                background: c.op === "delete" ? "rgba(17,17,17,0.12)" : c.op === "add" ? "rgba(17,17,17,0.9)" : "rgba(17,17,17,0.07)",
                color: c.op === "delete" ? ACCENT : c.op === "add" ? "#fff" : "#111",
              }}>{c.op}</span>
              <span style={{ fontSize: 11.5, fontWeight: 700, fontFamily: FONT, color: "#111" }}>{getSurface(c.surface)?.name ?? c.surface}</span>
              {c.offPalette && <span style={{ fontSize: 9.5, color: ACCENT, fontWeight: 800, fontFamily: FONT }}>OFF-PALETTE</span>}
            </div>
            <p style={{ fontSize: 10.5, color: "rgba(17,17,17,0.5)", ...S.mono, wordBreak: "break-all" }}>
              {c.property && <strong>{c.property}: </strong>}
              {c.op === "edit" && `${trunc(c.before)} → ${trunc(c.after)}`}
              {c.op === "move" && `${JSON.stringify(c.before)} → ${JSON.stringify(c.after)}`}
              {c.op === "resize" && `${JSON.stringify(c.before)} → ${JSON.stringify(c.after)}`}
              {c.op === "add" && `inserted ${c.elementRole}`}
              {c.op === "delete" && `removed ${c.elementRole || "element"}`}
            </p>
            <p style={{ fontSize: 10, color: "rgba(17,17,17,0.35)", ...S.mono }}>{c.sourceFile}{c.line ? `:${c.line}` : ""}</p>
            {c.notes && <p style={{ fontSize: 10.5, color: ACCENT, fontFamily: FONT, marginTop: 2 }}>{c.notes}</p>}
          </div>
        ))}
      </div>
      <div style={{ padding: 12, borderTop: "1px solid rgba(17,17,17,0.08)", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
        <button style={S.btn} onClick={() => copy(json, "json")}>{copied === "json" ? "Copied" : "Copy JSON"}</button>
        <button style={S.btn} onClick={() => copy(md, "md")}>{copied === "md" ? "Copied" : "Copy Markdown"}</button>
        <button style={S.btn} onClick={() => download(json, `canvas-changes-${Date.now()}.json`, "application/json")}>Download JSON</button>
        <button style={S.btn} onClick={() => download(md, `canvas-changes-${Date.now()}.md`, "text/markdown")}>Download MD</button>
        {issueRepo && (
          <button
            style={{ ...S.btn, gridColumn: "1 / -1", background: "#111111", color: "#FFFFFF", border: "1px solid #111111", opacity: changeLog.length === 0 ? 0.4 : 1, cursor: changeLog.length === 0 ? "not-allowed" : "pointer" }}
            disabled={changeLog.length === 0}
            onClick={openGitHubIssue}
            title={`Opens a prefilled GitHub issue on ${issueRepo} with the full change log`}
          >
            File GitHub issue → {issueRepo}
          </button>
        )}
      </div>
    </div>
  );
}

function trunc(v: unknown): string {
  const s = typeof v === "string" ? v : JSON.stringify(v);
  return s && s.length > 42 ? `"${s.slice(0, 42)}…"` : JSON.stringify(s);
}

// ─── Sessions panel ───────────────────────────────────────────────────────────
export function SessionsPanel() {
  const sessions = useCanvasState((s) => s.sessions);
  const changeLog = useCanvasState((s) => s.changeLog);
  const exportSession = (sessionId: string, fmt: "json" | "md") => {
    const sess = sessions.find((x) => x.sessionId === sessionId);
    if (!sess) return;
    const entries = changeLog.filter((c) => sess.changeIds.includes(c.id));
    const content = fmt === "json"
      ? JSON.stringify({ session: sess, project: config.projectName, repos: config.repos, changes: entries }, null, 2)
      : `# Session — ${sess.label || sess.sessionId}\n\nSaved ${sess.savedAt} · ${sess.changeCount} change(s) · ${sess.surfacesTouched.join(", ")}\n\n${toMarkdown(entries)}`;
    const blob = new Blob([content], { type: fmt === "json" ? "application/json" : "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${sess.sessionId}.${fmt}`; a.click();
    URL.revokeObjectURL(url);
  };
  return (
    <div style={{ overflowY: "auto", height: "100%" }}>
      <p style={S.h}>Save history · {sessions.length}</p>
      {sessions.length === 0 && (
        <p style={{ padding: "8px 16px", fontSize: 12.5, color: "rgba(17,17,17,0.45)", fontFamily: FONT, lineHeight: 1.6 }}>
          No saves yet. Hit <strong>Save session</strong> in the toolbar — every save is logged with what changed since the last one.
        </p>
      )}
      {sessions.slice().reverse().map((s) => (
        <div key={s.sessionId} style={{ padding: "10px 16px", borderBottom: "1px solid rgba(17,17,17,0.05)" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
            <span style={{ fontSize: 12.5, fontWeight: 800, fontFamily: FONT, color: "#111" }}>{s.label || s.sessionId}</span>
            <span style={{ fontSize: 10, color: "rgba(17,17,17,0.4)", ...S.mono }}>{s.sessionId}</span>
          </div>
          <p style={{ fontSize: 10.5, color: "rgba(17,17,17,0.5)", fontFamily: FONT, marginTop: 2 }}>
            {new Date(s.savedAt).toLocaleString()} · <strong>{s.changeCount}</strong> change{s.changeCount === 1 ? "" : "s"}
            {Object.entries(s.opsByType).map(([op, n]) => ` · ${op}×${n}`).join("")}
          </p>
          {s.surfacesTouched.length > 0 && (
            <p style={{ fontSize: 10, color: "rgba(17,17,17,0.4)", ...S.mono, marginTop: 2 }}>{s.surfacesTouched.join(", ")}</p>
          )}
          <div style={{ display: "flex", gap: 6, marginTop: 6 }}>
            <button style={{ ...S.btn, padding: "4px 10px", fontSize: 10.5 }} onClick={() => exportSession(s.sessionId, "json")}>Export JSON</button>
            <button style={{ ...S.btn, padding: "4px 10px", fontSize: 10.5 }} onClick={() => exportSession(s.sessionId, "md")}>Export MD</button>
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Search ───────────────────────────────────────────────────────────────────
export function SearchResults({ query, onJump }: { query: string; onJump: (id: string) => void }) {
  const q = query.trim().toLowerCase();
  const hits = useMemo(() =>
    !q ? [] : SURFACES.filter((s) =>
      s.name.toLowerCase().includes(q) || s.id.includes(q) || s.route.toLowerCase().includes(q) ||
      WORKSPACES.find((w) => w.id === s.workspace)?.name.toLowerCase().includes(q) ||
      s.nav.some((n) => n.trigger.toLowerCase().includes(q)),
    ).slice(0, 14),
  [q]);
  if (!q) return null;
  return (
    <div style={{ position: "absolute", top: 46, left: 0, width: 320, maxHeight: 420, overflowY: "auto", background: "#fff", borderRadius: 12, boxShadow: "0 16px 48px rgba(0,0,0,0.18)", border: "1px solid rgba(17,17,17,0.08)", zIndex: 200 }}>
      {hits.length === 0 && <p style={{ padding: 14, fontSize: 12.5, fontFamily: FONT, color: "rgba(17,17,17,0.45)" }}>No surfaces match "{query}"</p>}
      {hits.map((s) => (
        <div key={s.id} style={{ ...S.item, padding: "9px 14px" }} onMouseDown={() => onJump(s.id)}>
          <span style={{ width: 6, height: 6, borderRadius: 3, background: s.type === "screen" ? "#111" : ACCENT, flexShrink: 0 }} />
          <div>
            <p style={{ fontWeight: 700 }}>{s.name}</p>
            <p style={{ fontSize: 10.5, color: "rgba(17,17,17,0.4)" }}>{WORKSPACES.find((w) => w.id === s.workspace)?.name} · {s.type} · {s.route}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Insert menu ──────────────────────────────────────────────────────────────
export function InsertMenu({ surfaceId, onClose }: { surfaceId: string; onClose: () => void }) {
  const store = useCanvasStore();
  const add = (kind: "text" | "button" | "note") => {
    const id = `inserted-${kind}-${Date.now()}`;
    store.insertElement({
      elementId: id,
      surfaceId,
      anchorElement: "frame-root",
      kind,
      text: kind === "text" ? "New text" : kind === "button" ? "NEW ACTION" : "Designer note: …",
      color: kind === "button" ? "#FFFFFF" : config.ink,
      background: kind === "button" ? config.ink : kind === "note" ? "#FFFFFF" : "rgba(0,0,0,0)",
      fontSize: kind === "button" ? "12px" : "15px",
      dx: 120, dy: 300,
    });
    store.select(surfaceId, id);
    onClose();
  };
  return (
    <div style={{ position: "absolute", top: 46, right: 0, width: 200, background: "#fff", borderRadius: 12, boxShadow: "0 16px 48px rgba(0,0,0,0.18)", border: "1px solid rgba(17,17,17,0.08)", zIndex: 200, padding: 6 }}>
      {(["text", "button", "note"] as const).map((k) => (
        <button key={k} style={{ ...S.btn, width: "100%", border: "none", textAlign: "left", marginBottom: 2 }} onClick={() => add(k)}>
          {k === "text" ? "Text block" : k === "button" ? "Button" : "Designer note"}
        </button>
      ))}
    </div>
  );
}
